title: "Your Name"
description: "Personal website showcasing research, teaching, and writing"
url: "" # Add your website URL when deployed
baseurl: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
header_pages:
  - research.md
  - teaching.md
  - writing.md

# Social links (customize with your profiles)
social_links:
  github: username
  linkedin: username
  twitter: username

# Google Analytics (add your tracking ID here)
google_analytics: "" 