title: "Katrina Brown"
description: "Computer Science Student at Harvard University"
url: "katrinarbrown.github.io"
baseurl: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
header_pages:
  - index.md
  - research.md
  - speaking.md
  - teaching.md
  - work.md

# Social links
social_links:
  github: katrinarbrown
  linkedin: katrina-r-brown

# Google Analytics (add your tracking ID here)
google_analytics: "" 